name: install-test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ocaml-compiler:
          - 4.14.0
          - 4.08.1
    steps:
      - uses: actions/checkout@v2
      - uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - name: Install
        run: |
          sudo apt-get install libonig-dev
          opam install . -t
